name: CI

on: [push]

env:
  NODE_VERSION: '12.9.0'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build
      run: |
        npm install
        npm run build

    - name: archive publish files
      run: zip -r publish.zip node_modules .nuxt server static nuxt.config.js package.json

    - name: Upload publish files
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: publish.zip

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download publish files
      uses: actions/download-artifact@v1
      with:
        name: artifact

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: 'nuxt-ci'
        slot-name: 'gh'
        package: 'artifact/publish.zip'
