name: CI

on: [push]

env:
  AZURE_WEBAPP_NAME: your-app-name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '10.x'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build
    - name: archive publish files
      uses: actions/upload-artifact@v1
      with:
        name: publish
        path: .nuxt/
          # .nuxt/**/*
          # server/**/*
          # nuxt.config.js
          # package*.json

  deploy:
    name: Deploy to Azure
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: publish
    #- name: 'Deploy to Azure WebApp'
    #  uses: azure/webapps-deploy@v1
    #  with: 
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #    package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
